// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByGSOhZw8_40CkjmEdY7Alw1hphjtRSpo',
    appId: '1:1034880154706:web:d162d0cdc6617d6622738b',
    messagingSenderId: '1034880154706',
    projectId: 'mxpertz-bf306',
    authDomain: 'mxpertz-bf306.firebaseapp.com',
    storageBucket: 'mxpertz-bf306.appspot.com',
    measurementId: 'G-TVKWG4WCH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8CUe5WQPCQ3GVUaBWkCHkX_yu2FyQ8g',
    appId: '1:1034880154706:android:1af0b8b5331f21d322738b',
    messagingSenderId: '1034880154706',
    projectId: 'mxpertz-bf306',
    storageBucket: 'mxpertz-bf306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7EZyKq-6S9x4q0OfMBE-qsModDJgfGos',
    appId: '1:1034880154706:ios:9f9f28667e5a631a22738b',
    messagingSenderId: '1034880154706',
    projectId: 'mxpertz-bf306',
    storageBucket: 'mxpertz-bf306.appspot.com',
    iosBundleId: 'com.example.mxpertx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7EZyKq-6S9x4q0OfMBE-qsModDJgfGos',
    appId: '1:1034880154706:ios:554323f8bb90528822738b',
    messagingSenderId: '1034880154706',
    projectId: 'mxpertz-bf306',
    storageBucket: 'mxpertz-bf306.appspot.com',
    iosBundleId: 'com.example.mxpertx.RunnerTests',
  );
}
